import 'package:time6_7/app2/model/shop.dart';

List<Shop> controller = [
  Shop(
      id: 1,
      name: 'Japan Milk Bread',
      price: 2000,
      category: Category.bread,
      description: '',
      image: 'assets/images/japanmilkbread.jpg',
      size: ['s', 'm', 'l']),
  Shop(
    id: 2,
    name: 'Milk Bread',
    price: 3000,
    category: Category.bread,
    description: '',
    image: 'assets/images/milkbread.jpg',
    size: ['s', 'l'],
  ),
  Shop(
    id: 3,
    name: 'Chocolate Cake',
    price: 4000,
    category: Category.cake,
    description: '',
    image: 'assets/images/chocolatecake.jpg',
    size: ['m', 'l'],
  ),
  Shop(
    id: 4,
    name: 'Shop 4',
    price: 5000,
    category: Category.cake,
    description: '',
    image: 'assets/images/vanilacake.jpg',
    size: ['s', 'm'],
  ),
  Shop(
    id: 5,
    name: 'Chocolate Chunk Cookies',
    price: 6000,
    category: Category.cookeis,
    description: '',
    image: 'assets/images/chocolatechunkcookies.jpg',
    size: ['s', 'l', 'xl'],
  ),
  Shop(
    id: 6,
    name: 'American Cookies',
    price: 7000,
    category: Category.cookeis,
    description: '',
    image: 'assets/images/americancookies.jpg',
    size: ['m', 'xl'],
  ),
  Shop(
    id: 7,
    name: 'Dough Nut',
    price: 8000,
    category: Category.donut,
    description: '',
    image: 'assets/images/doughnut.jpg',
    size: ['l', 'xl'],
  ),
  Shop(
    id: 8,
    name: 'Chocolate Donut',
    price: 9000,
    category: Category.donut,
    description: '',
    image: 'assets/images/chocolatedonut.jpg',
    size: ['s', 'm', 'xl'],
  ),
  Shop(
    id: 9,
    name: 'Shop 9',
    price: 10000,
    category: Category.bread,
    description:
        "Indulge in the rich, moist, and decadent delight of our freshly baked cakes. Made with the finest ingredients, each bite melts in your mouth, offering a perfect balance of sweetness and texture. Whether you crave the velvety smoothness of chocolate, the light fluffiness of vanilla, or the fruity freshness of berries, our cakes are crafted to satisfy every sweet tooth. Perfect for birthdays, celebrations, or simply treating yourself, our cakes are a slice of happiness in every bite!",
    image: 'assets/images/japanmilkbread.jpg',
    size: ['s', 'l'],
  ),
  Shop(
    id: 10,
    name: 'Shop 10',
    price: 11000,
    category: Category.cake,
    description: '',
    image: 'assets/images/japanmilkbread.jpg',
    size: ['m', 'l', 'xl'],
  ),
];
